[project]
name = "webhook-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dstack-sdk>=0.2.1",
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
]
